-- 최근 검색어(스펙 008): 로그인 회원이 검색한 키워드를 최신순으로 보관(회원당 상한 15, 애플리케이션에서 유지).
-- 재검색은 unique(member_id, keyword) + ON CONFLICT DO UPDATE searched_at 으로 중복 없이 맨 앞 갱신.
CREATE TABLE member_recent_search (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT       NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    keyword     VARCHAR(50)  NOT NULL,
    searched_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_recent_search_member_keyword UNIQUE (member_id, keyword)
);

-- 최신순 조회·상한 초과분 제거에 사용.
CREATE INDEX idx_recent_search_member_time ON member_recent_search (member_id, searched_at DESC);
