-- 장소 후기(스펙 010): 코스·주차장 공통이라 place에 1:N으로 단다.
-- member_level은 작성 시점 회원 레벨의 스냅샷으로, 레벨별 목록·난이도 분포 집계와
-- "레벨 변경 후 이전 레벨 후기 수정 불가" 규칙의 기준이 된다(회원 레벨이 바뀌어도 불변).
-- 같은 회원이 같은 장소에 여러 번 쓸 수 있어 유니크 제약은 두지 않는다.
CREATE TABLE review (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id        BIGINT        NOT NULL REFERENCES place (id) ON DELETE CASCADE,
    member_id       BIGINT        NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    is_recommended  BOOLEAN       NOT NULL,
    difficulty      VARCHAR(20)   NOT NULL,
    congestion      VARCHAR(20)   NOT NULL,
    practice_method VARCHAR(20)   NOT NULL,
    content         VARCHAR(1000) NOT NULL,
    caution         TEXT,
    member_level    VARCHAR(20)   NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

-- 목록 keyset 커서(최신순), 레벨 필터·요약 집계, 작성자 기준 조회(차단 필터).
CREATE INDEX idx_review_place_created ON review (place_id, created_at DESC, id DESC);
CREATE INDEX idx_review_place_level ON review (place_id, member_level);
CREATE INDEX idx_review_member ON review (member_id);
