-- 후기 신고(같은 후기 중복 신고 방지). 접수·보관까지만 하고 후기 노출은 바꾸지 않는다.
-- unique가 (review_id, reporter_id) 인덱스를 겸한다.
CREATE TABLE review_report (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id   BIGINT      NOT NULL REFERENCES review (id) ON DELETE CASCADE,
    reporter_id BIGINT      NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    reason      VARCHAR(30) NOT NULL,
    detail      TEXT,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uq_review_report UNIQUE (review_id, reporter_id)
);

-- 회원 차단(단방향). 차단하면 차단한 쪽의 후기 목록에서만 상대 후기가 빠진다(요약 집계는 전체 기준).
-- unique가 (blocker_id, blocked_id) 인덱스를 겸해 목록 필터의 NOT EXISTS를 받쳐준다.
CREATE TABLE member_block (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT    NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    blocked_id BIGINT    NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_member_block UNIQUE (blocker_id, blocked_id),
    CONSTRAINT ck_member_block_not_self CHECK (blocker_id <> blocked_id)
);
