-- 사용자 연습 코스 목록(스펙 011): 코스 상세 [연습하기]로 담고, 이후 방문 여부를 기록한다.
-- 같은 장소는 한 행만 두고 재연습은 visit_count로 누적한다(목록이 같은 코스로 도배되지 않게).
-- 방문 판정은 클라이언트가 이동 추적으로 자동 호출하며 서버는 결과를 기록만 한다.
CREATE TABLE member_practice (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT       NOT NULL REFERENCES member (id) ON DELETE CASCADE,
    place_id    BIGINT       NOT NULL REFERENCES place (id) ON DELETE CASCADE,
    status      VARCHAR(20)  NOT NULL,            -- PLANNED | VISITED | NOT_VISITED
    visit_count INT          NOT NULL DEFAULT 0,  -- VISITED로 바뀔 때마다 +1
    visited_at  TIMESTAMP,                        -- 마지막 방문 시각
    skip_reason VARCHAR(30),                      -- NOT_VISITED일 때만
    skip_detail VARCHAR(100),                     -- skip_reason = OTHER일 때만
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uq_member_practice UNIQUE (member_id, place_id)
);

-- 목록은 최근 방문순(방문 이력이 없으면 담은 시각 기준)이라 정렬 키를 그대로 인덱스로 둔다.
CREATE INDEX idx_member_practice_recent
    ON member_practice (member_id, COALESCE(visited_at, created_at) DESC, id DESC);
