-- 회원
CREATE TABLE member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname   VARCHAR(30)  NOT NULL,
    email      VARCHAR(255),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_member_nickname UNIQUE (nickname)
);

-- 소셜 계정 (member 1:N, 안정 식별자 = provider + provider_id)
CREATE TABLE social_account (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT       NOT NULL,
    provider    VARCHAR(20)  NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_social_account_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uq_social_provider UNIQUE (provider, provider_id)
);

-- refresh token (해시 저장, 회원당 다중 세션, 회전 + 재사용 탐지)
CREATE TABLE refresh_token (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id            BIGINT       NOT NULL,
    token_hash           VARCHAR(255) NOT NULL,
    expires_at           TIMESTAMP    NOT NULL,
    revoked_at           TIMESTAMP,             -- 폐기 시각(삭제 대신 마킹 → 재제출 탐지)
    replaced_by_token_id BIGINT,                -- 회전 계보(감사)
    last_used_at         TIMESTAMP,             -- 마지막 사용(감사)
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    CONSTRAINT fk_refresh_token_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_token_member ON refresh_token (member_id);
