-- 코스 탐색(#47): place 도메인 신규. JOINED 상속(ADR 0002) — place(공통) + course/parking(place_id 공유 PK).
-- 위치는 PostGIS geometry(Point,4326). 목록은 place.location에 GiST 인덱스로 bbox·거리 쿼리.

-- 장소(공통)
CREATE TABLE place (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_type  VARCHAR(20)          NOT NULL,   -- 구분자: PARKING | COURSE
    name        VARCHAR(255)         NOT NULL,
    description TEXT,
    location    geometry(Point,4326) NOT NULL,   -- 대표 좌표(코스=시작점, 주차장=위치)
    created_at  TIMESTAMP            NOT NULL,
    updated_at  TIMESTAMP            NOT NULL
);
CREATE INDEX idx_place_location ON place USING GIST (location);

-- 코스(place 상속)
CREATE TABLE course (
    place_id        BIGINT PRIMARY KEY REFERENCES place (id),
    distance_meters INT,        -- 주행거리
    cautions        TEXT        -- 주의사항
);

-- 코스 연습태그(N:M) — PracticeType enum 저장(참조 테이블 없음)
CREATE TABLE course_practice_type (
    course_id     BIGINT      NOT NULL REFERENCES course (place_id),
    practice_type VARCHAR(30) NOT NULL,
    PRIMARY KEY (course_id, practice_type)
);

-- 코스 경로점(1:N)
CREATE TABLE waypoint (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT               NOT NULL REFERENCES course (place_id),
    waypoint_type VARCHAR(20)          NOT NULL,   -- START | VIA | DESTINATION
    sequence      SMALLINT             NOT NULL,   -- 경로 순서
    location      geometry(Point,4326) NOT NULL,
    name          VARCHAR(255),
    CONSTRAINT uq_waypoint_course_seq UNIQUE (course_id, sequence)
);

-- 주차장(place 상속) — 공영주차장 open DB 컬럼과 1:1(개별 컬럼)
CREATE TABLE parking (
    place_id             BIGINT PRIMARY KEY REFERENCES place (id),
    road_address         VARCHAR(255),
    lot_address          VARCHAR(255),
    management_no        VARCHAR(50),
    parking_type         VARCHAR(30),   -- 노외/노상/부설 등
    capacity             INT,           -- 주차면수
    is_free              BOOLEAN,
    has_accessible_space BOOLEAN,
    phone                VARCHAR(30),
    operator             VARCHAR(100),
    note                 TEXT,
    payment_methods      VARCHAR(100),  -- 예: "카드"
    base_minutes         INT,
    base_fee             INT,
    add_unit_minutes     INT,
    add_unit_fee         INT,
    day_ticket_hours     INT,
    day_ticket_fee       INT,
    monthly_fee          INT,
    weekday_hours        VARCHAR(50),   -- 예: "00:00-23:59"
    saturday_hours       VARCHAR(50),
    holiday_hours        VARCHAR(50)
);

-- 북마크(회원 ↔ place, 코스·주차장 공통)
CREATE TABLE bookmark (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id  BIGINT    NOT NULL REFERENCES member (id),
    place_id   BIGINT    NOT NULL REFERENCES place (id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_bookmark_member_place UNIQUE (member_id, place_id)
);
CREATE INDEX idx_bookmark_place ON bookmark (place_id);
